### ISSUE TITLE
bootkube crash: panic in kubernetes:pkg/util/runtime/runtime.go

### ISSUE THREAD

**Issue by abourget** [kubernetes-incubator/bootkube#273]
I got this panic when running `bootkube` (on commit c1381398a277cc3d7981e70a4306d1ca88b1c60c)

```I0116 05:09:09.929019    1412 event.go:217] Event(api.ObjectReference{Kind:"DaemonSet", Namespace:"kube-system", Name:"kube-apiserver", UID:"b9912153-dba9-11e6-b521-022f9fd4e73b", APIVersion:"extensions", ResourceVersion:"393", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted pod: kube-apiserver-q10mb
E0116 05:09:10.990973    1412 runtime.go:64] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/abourget/go/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:70
/home/abourget/go/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:63
/home/abourget/go/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:49
/usr/local/go/src/runtime/asm_amd64.s:479
/usr/local/go/src/runtime/panic.go:458
/usr/local/go/src/runtime/panic.go:62
/usr/local/go/src/runtime/sigpanic_unix.go:24
/home/abourget/go/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/controller/node/rate_limited_queue.go:244
/home/abourget/go/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/controller/node/nodecontroller.go:822
/home/abourget/go/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/controller/node/nodecontroller.go:486
/home/abourget/go/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/controller/node/nodecontroller.go:365
/home/abourget/go/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:96
/home/abourget/go/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:97
/home/abourget/go/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:52
/usr/local/go/src/runtime/asm_amd64.s:2086
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xecf162]

goroutine 8257 [running]:
panic(0x289f400, 0xc4200120d0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/abourget/go/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:56 +0x126
panic(0x289f400, 0xc4200120d0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/controller/node.(*RateLimitedTimedQueue).Remove(0x0, 0xc42589a2d0, 0x2a, 0x0)
	/home/abourget/go/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/controller/node/rate_limited_queue.go:244 +0x22
github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/controller/node.(*NodeController).cancelPodEviction(0xc422c6e2c0, 0xc425264278, 0x2d93300)
	/home/abourget/go/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/controller/node/nodecontroller.go:822 +0x123
github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/controller/node.(*NodeController).monitorNodeStatus(0xc422c6e2c0, 0x458280, 0xc4235fde50)
	/home/abourget/go/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/controller/node/nodecontroller.go:486 +0x1208
github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/controller/node.(*NodeController).Run.func1.1()
	/home/abourget/go/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/controller/node/nodecontroller.go:365 +0x2e
github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc42119e770)
	/home/abourget/go/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:96 +0x5e
github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc42119e770, 0x12a05f200, 0x0, 0x461801, 0xc4200f14a0)
	/home/abourget/go/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:97 +0xad
github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc42119e770, 0x12a05f200, 0xc4200f14a0)
	/home/abourget/go/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:52 +0x4d
created by github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/controller/node.(*NodeController).Run.func1
	/home/abourget/go/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/controller/node/nodecontroller.go:368 +0x2a4
```

My config is a 3-node control plane, on Container Linux 1235.6.0, using v1.5.2_coreos0 for all hyperkube images (as well as kubelet through rkt), with `--storage-backend=etcd3` and `--apiserver-count=3` on the _apiserver_ (that were tweaked from the stock bootkube rendered templates). My `kubeconfig` has an AWS Load balancer as the `server:`.

Checkpoint-installer installs quay.io/coreos/pod-checkpointer:443f843edfee6be39a84d13c8cd060275f6f972e

The 3 etcd were all successfully connected. Some output, which include some funky logs though:

```
2017-01-16 05:06:06.212440 N | discovery: found peer 77c90a1cd33a7497 in the cluster
2017-01-16 05:06:06.212468 N | discovery: found self 3ea425961126050c in the cluster
2017-01-16 05:06:06.212475 N | discovery: found 2 peer(s), waiting for 1 more
2017-01-16 05:06:53.573931 N | discovery: found peer 394f411c99c9daf8 in the cluster
2017-01-16 05:06:53.573958 N | discovery: found 3 needed peer(s)
...
2017-01-16 05:09:05.536713 W | etcdserver: apply entries took too long [489.774797ms for 1 entries]
2017-01-16 05:09:05.537149 W | etcdserver: avoid queries with large range/delete range!
2017-01-16 05:09:22.018630 W | wal: sync duration of 2.470065612s, expected less than 1s
2017-01-16 05:09:23.521858 W | wal: sync duration of 1.408209818s, expected less than 1s
2017-01-16 05:09:26.083712 I | raft: 3ea425961126050c is starting a new election at term 3
2017-01-16 05:09:26.083756 I | raft: 3ea425961126050c became candidate at term 4
2017-01-16 05:09:26.083772 I | raft: 3ea425961126050c received MsgVoteResp from 3ea425961126050c at term 4
2017-01-16 05:09:26.083786 I | raft: 3ea425961126050c [logterm: 3, index: 1943] sent MsgVote request to 394f411c99c9daf8 at term 4
2017-01-16 05:09:26.083799 I | raft: 3ea425961126050c [logterm: 3, index: 1943] sent MsgVote request to 77c90a1cd33a7497 at term 4
2017-01-16 05:09:26.083810 I | raft: raft.node: 3ea425961126050c lost leader 394f411c99c9daf8 at term 4
2017-01-16 05:09:26.256899 I | raft: 3ea425961126050c received MsgVoteResp from 77c90a1cd33a7497 at term 4
2017-01-16 05:09:26.256934 I | raft: 3ea425961126050c [quorum:2] has received 2 MsgVoteResp votes and 0 vote rejections
2017-01-16 05:09:26.256958 I | raft: 3ea425961126050c became leader at term 4
2017-01-16 05:09:26.256976 I | raft: raft.node: 3ea425961126050c elected leader 3ea425961126050c at term 4
2017-01-16 05:10:09.144654 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 448.226631ms)
2017-01-16 05:10:09.144674 W | etcdserver: server is likely overloaded
2017-01-16 05:10:09.144684 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 448.286716ms)
2017-01-16 05:10:09.144690 W | etcdserver: server is likely overloaded
2017-01-16 05:10:24.349185 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 206.463022ms)
2017-01-16 05:10:24.349270 W | etcdserver: server is likely overloaded
```

This happens after a while, when `bootkube start` is running..

**Comment by aaronlevy** [comment]
The commit you mention is off of a branch in my own fork -- it's not expected to be stable at all. Since the time that I created that branch the etcd-operator & bootkube interaction has changed. The current work is ongoing:

I would suggest following https://github.com/kubernetes-incubator/bootkube/pull/259 for most up to date work thus far.
