### ISSUE TITLE
bootkube panics and exits when third party resources are present 

### ISSUE THREAD

**Issue by joshrosso** [kubernetes-incubator/bootkube#334]
## Issue
When launching bootkube with a pre-existing etcd present, if `/registry/thirdparty` resources are present in etcd, bootkube will panic and exit as follows.

```
Feb 25 02:21:37 ip-10-0-47-164 bootkube-start[5131]: [ 1158.791945] bootkube[5]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 25 02:21:37 ip-10-0-47-164 bootkube-start[5131]: [ 1158.792323] bootkube[5]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xe552ad]
Feb 25 02:21:37 ip-10-0-47-164 bootkube-start[5131]: [ 1158.792512] bootkube[5]: goroutine 44 [running]:
Feb 25 02:21:37 ip-10-0-47-164 bootkube-start[5131]: [ 1158.792671] bootkube[5]: panic(0x28ca700, 0xc420010050)
Feb 25 02:21:37 ip-10-0-47-164 bootkube-start[5131]: [ 1158.792878] bootkube[5]:         /usr/local/go/src/runtime/panic.go:500 +0x1a1
Feb 25 02:21:37 ip-10-0-47-164 bootkube-start[5131]: [ 1158.793035] bootkube[5]: github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/apimachinery/registered.(*APIRegistrationManager).RESTMapper(0xc4200fe500, 0x0, 0x0, 0x0, 0xc422807a08, 0x53eb80)
Feb 25 02:21:37 ip-10-0-47-164 bootkube-start[5131]: [ 1158.793205] bootkube[5]:         /go/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/apimachinery/registered/registered.go:313 +0x24d
Feb 25 02:21:37 ip-10-0-47-164 bootkube-start[5131]: [ 1158.793365] bootkube[5]: github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/apimachinery/registered.(*APIRegistrationManager).RESTMapper-fm(0x0, 0x0, 0x0, 0xc4227a2600, 0xc422807a40)
```

After some trial and error, I found the following keys were causing the above error.

```
# etcdctl get --prefix=true --keys-only=true /registry | grep thirdparty
/registry/thirdpartyresources/auth-code.oidc.coreos.com
/registry/thirdpartyresources/auth-request.oidc.coreos.com
/registry/thirdpartyresources/o-auth2-client.oidc.coreos.com
/registry/thirdpartyresources/password.oidc.coreos.com
/registry/thirdpartyresources/refresh-token.oidc.coreos.com
/registry/thirdpartyresources/signing-key.oidc.coreos.com
```

Removal of the `thirdparty` keys, as seen below, allows bootkube to start successfully.
```
etcdctl get --prefix=true --keys-only /registry | grep thirdparty | xargs -L1 etcdctl del
```

This issue was discovered while troubleshooting #333. 

## Versions
k8s [hyperkube] version: [1.5.2_coreos.2](https://github.com/coreos/kubernetes/tree/v1.5.2+coreos.2)
version: [v0.3.7](https://github.com/kubernetes-incubator/bootkube/tree/v0.3.7)
os: 
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1235.12.0
VERSION_ID=1235.12.0
BUILD_ID=2017-02-23-0222
PRETTY_NAME="Container Linux by CoreOS 1235.12.0 (Ladybug)"
```

**Comment by aaronlevy** [comment]
Just noting that currently bootkube is not meant to be used against an existing cluster. However, there may be situations later where we do want this behavior (e.g. maybe disaster recovery is built into bootkube at some point) - so I'll keep this open.
